service:
  name: ab3-frontend-deploy

provider:
  name: aws
  region: us-east-1
  profile: ab3

resources:
  Resources:
    CodeBuildRole:
      Type: AWS::IAM::Role
      Properties: 
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement: 
            - Effect: Allow
              Principal: 
                Service: 
                  - codebuild.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: ${self:service.name}-build-policy
            PolicyDocument: 
              Version: '2012-10-17'
              Statement: 
                - Effect: Allow
                  Action:
                    - logs:*
                  Resource:
                    Fn::Join:
                      - ':'
                      - - arn:aws:logs
                        - !Ref AWS::Region
                        - !Ref AWS::AccountId
                        - log-group
                        - /aws/codebuild/ab3-frontend-deploy
                        - '*'
                        - '*'
                - Effect: Allow
                  Action: s3:PutObject
                  Resource: 
                    Fn::Join:
                      - ':'
                      - - arn:aws:s3
                        - ''
                        - ''
                        - ${file(./config.json):bucket}/*
                - Effect: Allow
                  Action: cloudfront:CreateInvalidation
                  Resource: 
                    Fn::Join:
                      - ':'
                      - - arn:aws:cloudfront
                        - ''
                        - !Ref AWS::AccountId
                        - distribution/${file(./config.json):distribution}
    CodeBuildProject:
      Type: AWS::CodeBuild::Project
      Properties:
        Name: ${self:service.name}
        Description: My website builder
        ServiceRole: !Ref CodeBuildRole
        Artifacts:
          Type: NO_ARTIFACTS
        Environment:
          ComputeType: BUILD_GENERAL1_SMALL
          Image: aws/codebuild/standard:2.0
          Type: LINUX_CONTAINER
          EnvironmentVariables:
            - Name: STAGE
              Value: ${file(./config.json):stage}
              Type: PLAINTEXT
            - Name: WEBSITE_BUCKET
              Value: ${file(./config.json):bucket}
              Type: PLAINTEXT
            - Name: CLOUDFRONT_DISTRIBUTION_ID
              Value: ${file(./config.json):distribution}
              Type: PLAINTEXT
        Source:
          Location: https://github.com/rossmcewan/react-redux-realworld-example-app
          Type: GITHUB
        SourceVersion: master
        Triggers:
          Webhook: true